// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhpazywrzzaoosdlhppf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ocGF6eXdyenphb29zZGxocHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODQ4NzgsImV4cCI6MjA2NzU2MDg3OH0.6uTaj9jVL70XQUtN3P_IDdhIxdWQ21BbmZ0qeStIGZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});